@api_url = http://localhost:3333

# @name create_user
POST {{api_url}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@example.com",
  "password": "12345678"
}

###

# @name sign_in
POST {{api_url}}/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "gabriel@example.com",
  "password": "12345678"
}
