@baseUrl = http://localhost:3333
@createdAt = {{$datetime iso8601}}
@authToken1 = Bearer {{signIn1.response.body.accessToken}}
@authToken2 = Bearer {{signIn2.response.body.accessToken}}
@categoryId1 = {{listCategories1.response.body.$[0].id}}
@categoryId2 = {{listCategories2.response.body.$[0].id}}
@bankAccountId1 = {{listBankAccounts1.response.body.$[0].id}}
@bankAccountId2 = {{listBankAccounts2.response.body.$[0].id}}
@transactionId1 = {{listTransactions1.response.body.$[0].id}}
@transactionId2 = {{listTransactions2.response.body.$[0].id}}

###

// @name signUp1
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "12345678"
}

###

// @name signUp2
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "Richard Roe",
  "email": "richard.roe@example.com",
  "password": "12345678"
}

###

// @name signIn1
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "12345678"
}

###

// @name signIn2
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "richard.roe@example.com",
  "password": "12345678"
}

###

// @name me1
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name me2
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: {{authToken2}}

###

// @name listCategories1
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name listCategories2
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{authToken2}}

###

// @name createBankAccount1
POST {{baseUrl}}/bank-accounts
Content-Type: application/json
Authorization: {{authToken1}}

{
  "name": "Nubank",
  "color": "#7950F2",
  "initialBalance": 1000,
  "type": "CHECKING"
}

###

// @name createBankAccount2
POST {{baseUrl}}/bank-accounts
Content-Type: application/json
Authorization: {{authToken2}}

{
  "name": "Inter",
  "color": "#FF7A00",
  "initialBalance": 2000,
  "type": "CASH"
}

###

// @name listBankAccounts1
GET {{baseUrl}}/bank-accounts
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name listBankAccounts2
GET {{baseUrl}}/bank-accounts
Content-Type: application/json
Authorization: {{authToken2}}

###

// @name updateBankAccount1
PUT {{baseUrl}}/bank-accounts/{{bankAccountId1}}
Content-Type: application/json
Authorization: {{authToken1}}

{
  "name": "Nubank 2.0",
  "color": "#7950F2",
  "initialBalance": 10000,
  "type": "CHECKING"
}

###

// @name updateBankAccount1Forbidden
PUT {{baseUrl}}/bank-accounts/{{bankAccountId2}}
Content-Type: application/json
Authorization: {{authToken1}}

{
  "name": "Inter 2.0",
  "color": "#FF7A00",
  "initialBalance": 20000,
  "type": "CASH"
}

###

// @name deleteBankAccount1
DELETE {{baseUrl}}/bank-accounts/{{bankAccountId1}}
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name deleteBankAccount1Forbidden
DELETE {{baseUrl}}/bank-accounts/{{bankAccountId2}}
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name createTransaction1
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: {{authToken1}}

{
  "bankAccountId": "{{bankAccountId1}}",
  "categoryId": "{{categoryId1}}",
  "name": "Salário",
  "value": 6000,
  "date": "{{createdAt}}",
  "type": "INCOME"
}

###

// @name createTransaction2
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: {{authToken2}}

{
  "bankAccountId": "{{bankAccountId2}}",
  "categoryId": "{{categoryId2}}",
  "name": "Boleto",
  "value": 1000,
  "date": "{{createdAt}}",
  "type": "EXPENSE"
}

###

// @name createTransaction1Forbidden
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: {{authToken1}}

{
  "bankAccountId": "{{bankAccountId2}}",
  "categoryId": "{{categoryId2}}",
  "name": "Salário",
  "value": 6000,
  "date": "{{createdAt}}",
  "type": "INCOME"
}

###

// @name listTransactions1
GET {{baseUrl}}/transactions
    ?month=8
    &year=2023
    &type=INCOME
    &bankAccountId={{bankAccountId1}}
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name listTransactions2
GET {{baseUrl}}/transactions
Content-Type: application/json
Authorization: {{authToken2}}

###

// @name updateTransaction1
PUT {{baseUrl}}/transactions/{{transactionId1}}
Content-Type: application/json
Authorization: {{authToken1}}

{
  "bankAccountId": "{{bankAccountId1}}",
  "categoryId": "{{categoryId1}}",
  "name": "Salário",
  "value": 12000,
  "date": "{{createdAt}}",
  "type": "INCOME"
}

###

// @name updateTransaction1ParamsForbidden
PUT {{baseUrl}}/transactions/{{transactionId1}}
Content-Type: application/json
Authorization: {{authToken1}}

{
  "bankAccountId": "{{bankAccountId2}}",
  "categoryId": "{{categoryId2}}",
  "name": "Salário",
  "value": 12000,
  "date": "{{createdAt}}",
  "type": "INCOME"
}

###

// @name updateTransaction1Forbidden
PUT {{baseUrl}}/transactions/{{transactionId2}}
Content-Type: application/json
Authorization: {{authToken1}}

{
  "bankAccountId": "{{bankAccountId1}}",
  "categoryId": "{{categoryId1}}",
  "name": "Salário",
  "value": 12000,
  "date": "{{createdAt}}",
  "type": "INCOME"
}

###

// @name deleteTransaction1
DELETE {{baseUrl}}/transactions/{{transactionId1}}
Content-Type: application/json
Authorization: {{authToken1}}

###

// @name deleteTransaction1Forbidden
DELETE {{baseUrl}}/transactions/{{transactionId2}}
Content-Type: application/json
Authorization: {{authToken1}}
